# -*- coding: utf-8 -*-
"""testapp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQ6Dc1i1z6T3sU3H54jo6rJYlnTq29Eh
"""

import streamlit as st

# Streamlit-app
def main():
    st.title("VårdGPT")

    # Förslag på frågor
    suggested_questions = [
        "Vilka egenskaper är bra att ha som sjuksköterska?",
        "Vilka delar av landet erbjuder flest heltidsjobb inom vården?",
        "Vilka ansvarsområden har ofta undersköterskor?"
    ]

    # Visa förslag på frågor
    selected_question = st.selectbox("Välj en fråga:", suggested_questions)

    # Användarens egen fråga
    custom_question = st.text_input("Skriv din egen fråga här:")

    # Om användaren skrivit in en egen fråga
    if custom_question:
        selected_question = custom_question

    # Visa svar endast om en fråga är vald eller en egen fråga skrivs in
    if selected_question:
        # Tillfälligt standardiserat svar
        response = "Jag kan inte detta än."
        st.text("Svar:")
        st.write(response)

if __name__ == "__main__":
    main()